### ISSUE TITLE
node interceptors corrupt incoming binary bodies

### ISSUE THREAD

**Issue by FauxFaux** [mswjs/interceptors#109]
https://github.com/mswjs/interceptors/blob/c6f440a2b1abb3b230094b8c794a0dc35d2f1981/src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts#L8

`chunk` here is normally(?) a `Buffer`, and `+=` is silently calling `.toString(encoding='utf-8')` on it, which is lossy. This prevents the interception of transfer encoded bodies, as this corrupts `gzip` data.

**Comment by thomas-p-wilson** [comment]
Can confirm that

```
export function getIncomingMessageBody(res: IncomingMessage): Promise<string> {
  let responseBody = Buffer.from('');

  return new Promise((resolve, reject) => {
    res.once('error', reject)
    res.on('data', (chunk) => { responseBody = Buffer.concat([responseBody, chunk]); })
    res.once('end', () => {
      resolve(responseBody)
    })
  })
}
```

resolves my particular problem with gzipped response contents. I expect this would also resolve OP's problem. I think it's safe to say that the above does not represent an acceptable solution due to the likely overwhelming reliance on the response body being a string.

Some general thoughts:
- `let responseBody = Buffer.from('');` should be provided a fixed size based on the `Content-Length` header if at all possible, whereby we could avoid concatenating buffers needlessly. This falls over if Content-Length is unavailable or incorrect.
- Could we default to returning a string, but provide the developer an option to receive the buffer instead? Not sure if there's the possibility of supplying such an option.

Alternately, we could handle the gzip compression ourselves. To me this seems to get into the weeds a bit too much, and risks broadening the scope of the library to handle other forms of compression, inflate/deflate, and other such things. But for the sake of the conversation, the following would potentially be an acceptable solution to this particular problem as it continues to return a string as the response body, as would be expected by existing users of this library:

```
import { createGunzip } from 'zlib';

export function getIncomingMessageBody(res: IncomingMessage): Promise<string> {
  let responseBody = '';
  let stream = res;
  if (res.headers['content-encoding'] === 'gzip') {
    const gzip = createGunzip();
    stream = res.pipe(gzip);
  }

  return new Promise((resolve, reject) => {
    stream.once('error', reject)
    stream.on('data', (chunk) => { responseBody += chunk); })
    stream.once('end', () => {
      resolve(responseBody)
    })
  })
}
```

Thoughts from contributors? Happy to wrap this up in a PR pending any amendments identified by the team.

**Comment by kettanaito** [comment]
Hey, @thomas-p-wilson. Thank you for the insights and suggestions above.

I think treating the response body as a buffer is a good direction to go. 

> the above does not represent an acceptable solution due to the likely overwhelming reliance on the response body being a string.

However, the current implementation treats the response body as a string anyway:

https://github.com/mswjs/interceptors/blob/573009ac5432c5464245770ab43a5241f62d3a46/src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts#L4

So this isn't something the suggested solution introduces. 

> [response body buffer] should be provided a fixed size based on the Content-Length header

Completely agree. 

> Could we default to returning a string, but provide the developer an option to receive the buffer instead? Not sure if there's the possibility of supplying such an option.

The public API always returns the response body as a string in the `IsomorphicResponse` object:

https://github.com/mswjs/interceptors/blob/573009ac5432c5464245770ab43a5241f62d3a46/src/createInterceptor.ts#L25-L30

At the moment I don't see a reason to change this contract. If the response body is a buffer or a binary, it can be converted to a string and exposed in the isomorphic response for any further manipulations. Keeping the response body as a string also allows request interception in a child process, where the response body is being sent over IPC between parent/child processes (and thus must be a string). 

I agree with your suggestions above and would love to see a pull request from you, @thomas-p-wilson! If I'm not mistaken, we could start by:

1. Adding at least 2 unit tests to `getIncomingMessageBody` function (string response body and gzipped response body, which surfaces the issue).
2. Treating the response body as a `Buffer.from('')` internally.
3. Setting a fixed size of the response body buffer based on the `res.headers['content-length']` header. Adjusting the response body concatenation, if necessary, in the `res.on('data')` listener.

**Comment by thomas-p-wilson** [comment]
Hey @kettanaito! I accept your feedback, and will submit a PR in the next couple of days incorporating your bullet point requirements. Cheerio!

**Comment by thomas-p-wilson** [comment]
Digging through the test structure. As the test directory hierarchy doesn't match 1:1 with the source directory hierarchy, I'm unsure where you would like `getIncomingMessageBody`-specific unit tests. I see tests against that particular utility spread across six separate test files. Do you have a preference?

**Comment by thomas-p-wilson** [comment]
Feel free to ignore me. I'm clearly illiterate...

**Comment by thomas-p-wilson** [comment]
With respect to the following:

> 2. Treating the response body as a Buffer.from('') internally.
> 3. Setting a fixed size of the response body buffer based on the res.headers['content-length'] header. Adjusting the response body concatenation, if necessary, in the res.on('data') listener.

We need not change this. Can pipe the response through `zlib.createGunzip()` which makes it effectively transparent. The concatenation method remains suitable.

**Comment by thomas-p-wilson** [comment]
@kettanaito PR is up. It's a relatively simple change. Please review and let me know if it's up to snuff :)

For anybody landing here, a suitable workaround until this makes it to a release is to add the following somewhere prior to initialization of your interceptors:

```
import * as zlib from 'zlib';
import { Stream } from 'stream';
import * as incomingMessageBody from '@mswjs/interceptors/lib/interceptors/ClientRequest/utils/getIncomingMessageBody';

Object.defineProperty(incomingMessageBody, 'getIncomingMessageBody', {
  value: function(res) {
    let responseBody = '';
    let stream: Stream = res;
    if (res.headers['content-encoding'] === 'gzip') {
      const gzip = zlib.createGunzip();
      stream = res.pipe(gzip);
    }
    return new Promise(function (resolve, reject) {
      stream.once('error', reject);
      stream.on('data', function (chunk) { return (responseBody += chunk); });
      stream.once('end', function () {
        resolve(responseBody);
      });
    });
  }
});

```

This is the approach I have taken until the above PR lands in a release. It has so far served me well.
