### ISSUE TITLE
Node request interceptor is getting skipped for the response interceptor

### ISSUE THREAD

**Issue by nravic** [mswjs/interceptors#111]
When attaching a debugger to the following code (with breakpoints set at the request and response interceptors):

```typescript
export class NodeHttpClient implements Provider<AxiosLike> {
	value() {
		const interceptor = createInterceptor({
			modules: nodeInterceptors,
			resolver(request) {},
		});

		interceptor.on('request', (request) => {
			console.log(request);
			return request;
		});

		interceptor.on('response', (request, response) => {
                        console.log(request, response);
                        return response;
		});

		const instance = axios.create();
		instance.defaults.adapter = require('axios/lib/adapters/http');
		interceptor.apply();
		return instance;
	}
}
```
it appears as if the request interceptor is skipped and execution is started with the response interceptor when a request is initiated. I've tried this with other interceptor modules and they all behave the same way. 

I'd appreciate any help looking into this or a direction to be pointed towards to resolve this, especially if it's something minor I'm overlooking. 

Thank you!

**Comment by kettanaito** [comment]
Hey, @nravic. Thanks for reporting this.

It looks like the current [ClientRequest interceptor](https://github.com/mswjs/interceptors/blob/ae27f7466b66340ab5bea1175b3c152c235b08d0/src/interceptors/ClientRequest/createClientRequestOverride.ts) doesn't emit the "request" event at all. The same can be said about the XMLHttpRequest interceptor. It may be a typo (response -> request), or simply a bug. 

Please, would you be interested in opening a pull request to add `observer.emit('request', isoRequest)` calls after these lines?

https://github.com/mswjs/interceptors/blob/ae27f7466b66340ab5bea1175b3c152c235b08d0/src/interceptors/ClientRequest/createClientRequestOverride.ts#L179-L184

https://github.com/mswjs/interceptors/blob/ae27f7466b66340ab5bea1175b3c152c235b08d0/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L243-L248
