### ISSUE TITLE
Jest@27 compatibility

### ISSUE THREAD

**Issue by kettanaito** [mswjs/interceptors#126]
- [jest@27.0 Release notes](https://github.com/facebook/jest/releases/tag/v27.0.0)

## Issues

- [x] JSDOM is no longer the default test environment.
- [x] `setImmediate` is not defined (#123)
- [x] `TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an instance of Object`
- [x] Test functions cannot both take a 'done' callback and return something. Either use a 'done' callback, or return a promise. (previously less strict). 
- [x] `ReferenceError: browserType.launch: setImmediate is not defined` when running in-browser tests.

**Comment by kettanaito** [comment]
## Invalid `options.agent`

The error originates from this Agent check in Node.js:

```js
let agent = options.agent;
const defaultAgent = options._defaultAgent || Agent.globalAgent;
if (agent === false) {
  agent = new defaultAgent.constructor();
} else if (agent === null || agent === undefined) {
  if (typeof options.createConnection !== 'function') {
    agent = defaultAgent;
  }
  // Explicitly pass through this statement as agent will not be used
  // when createConnection is provided.
} else if (typeof agent.addRequest !== 'function') {
  throw new ERR_INVALID_ARG_TYPE('options.agent',
                                  ['Agent-like Object', 'undefined', 'false'],
                                  agent);
}
```

—[Source](https://github.com/nodejs/node/blob/78af363aa7b8817a575faf1c3de58e47d64a1f8b/lib/_http_client.js#L129-L143)

**Comment by jonkoops** [comment]
@kettanaito Could we get a release for these fixes?
