### ISSUE TITLE
interceptor.on('response'...) not catching any events

### ISSUE THREAD

**Issue by cameronbrill** [mswjs/interceptors#137]
i have the following code in my project:
```typescript
const interceptor = new (createInterceptor as any)({
    modules: nodeInterceptors,
});
interceptor.apply();

interceptor.on('request', (request: IsomorphicRequest) => {
    this.logger.log(
        '=============request============\n\n%s\n\n========================',
        JSON.stringify(request)
    );
});
interceptor.on(
    'response',
    (req: IsomorphicRequest, res: IsomorphicResponse) => {
        this.logger.log(
            '=============request============\n\n%s\n=============response============\n\n%s\n\n========================',
            JSON.stringify(req),
            JSON.stringify(res)
        );
    }
);

process.on('disconnect', () => {
    interceptor.restore();
});
```
the listener on `request` works fine, and logs every request. But, the listener on `response` is never logging anything. am i missing any setup/config?

**Comment by kettanaito** [comment]
Hey, @cameronbrill.

The only thing I can spot is that you're not providing any `resolver` option to the `createInterceptor` call. That option is mandatory, even if you don't plan on mocking responses.

```diff
const interceptor = new (createInterceptor as any)({
    modules: nodeInterceptors,
+  resolver() {}
});
```

You can see how to set up the events in the [respective test suites](https://github.com/mswjs/interceptors/tree/a3dda002d69399d0706a9aa8531f79ee4a089ab4/test/events), but apart from that your setup looks good to me.

**Comment by kettanaito** [comment]
I'm treating the inactivity as that the issue was resolved. 

Any responses, mocked or not, will be propagated to the "response" event, as long as they happen in the same process as the `createInterceptor` function was called.
