### ISSUE TITLE
xmldom security vulnerability

### ISSUE THREAD

**Issue by WayneEllery** [mswjs/interceptors#145]
## Describe the bug
xmldom 0.6.0 has a moderate security vulnerability: https://git.realestate.com.au/advisories/GHSA-5fg8-2547-mr8q

xmldom is a dependency of `@mswjs/interceptors`

Upgrading to 0.7.0 addresses the vulnerability

## Environment

- `msw: 0.33.2`
- `nodejs: 14.17.4`
- `npm: 6.14.14`

**Comment by kettanaito** [comment]
Hey, @WayneEllery. Thanks for raising this. 

I've moved the issue to the "interceptors" repository to be closer to the source. I'd be happy to update the `xmldom` dependency once it lands.

**Comment by Schwad** [comment]
We're watching this 👀  -- so locally we're pointing to the github 0.7.0 release and we'll be sure to update interceptors the minute you have that updated. Thanks!
