### ISSUE TITLE
options.modules.map is not a function

### ISSUE THREAD

**Issue by bartbutenaers** [mswjs/interceptors#157]
Dear,

I have the impression that will end up in a very silly question, but can't find the answer by myself...

When I do this in my NodeJs (version v12.19.0) application:

```js
const { createInterceptor } = require('@mswjs/interceptors');
const nodeInterceptors = require('@mswjs/interceptors/lib/presets/node');

var interceptor = createInterceptor({
    modules: nodeInterceptors,
    resolver(request, ref) {
            // Optionally, return a mocked response.
    },
})

interceptor.apply();
```
Then the `apply` call results in following exception:

```sh
createInterceptor.ts:73 Uncaught TypeError: options.modules.map is not a function
    at Object.apply (createInterceptor.ts:73)
    at eval (eval at HttpLoggerNode (http_logger.js:41), <anonymous>:1:18)
    at new HttpLoggerNode (http_logger.js:41)
    at Object.createNode (util.js:86)
    at Flow.start (Flow.js:205)
    at start (index.js:371)
```

Does anybody see what I am doing wrong?

P.S. I had no errors while installing version 0.12.7 of this library (using `npm install @mswjs/interceptors`).

Thanks !!!
Bart

**Comment by bartbutenaers** [comment]
Hi @kettanaito,
Thanks for you fast response!
I have created a local git clone of your repo.  
Could you please explain in short the steps I have to follow for building this library?
Thanks!!

**Comment by kettanaito** [comment]
I had a great chat with @slightlytyler about module formats, and the issue you're experiencing isn't an issue per se. 

We export the `nodeInterceptors` as an array of functions using the _default_ export. Thing is, there's no "default" export in CommonJS (where you're using `require`), it must always be an object. Thus, the `export default` gets translated as `module.exports = { default: nodeInterceptors }`. 

We could change the export type to use a named export but I see little reason in doing so.
