### ISSUE TITLE
Two concurrent requests to the same host override each other

### ISSUE THREAD

**Issue by kettanaito** [mswjs/interceptors#2]
## Steps to reproduce

```js
http.request('http://httpbin.org/get')
http.request('http://httpbin.org/get', { headers: { 'foo': 'bar' } })
```

## Current behavior

When accessed in the middleware function, the second request will not have the `headers` present, as the first request interferes with it.

## Expected behavior

Each of the hosts must be processed separately.

## Clues

- Request identity is not respected
- Watch out for mutable entities, make sure they never persist between requests

**Comment by kettanaito** [comment]
This needs to be verified in an actual usage scenario.

**Comment by sean-hernon** [comment]
Does this affect only the headers? I am planning to use the library to intercept and log outgoing http requests. I have a single middleware function that logs the method and url.href and _does not_ return a mocked response. Does this sound like a scenario that will encounter the issue, with a high enough volume of requests and possible matching urls?

Thank you for your advice.

**Comment by kettanaito** [comment]
Hi, @sean-hernon. I believe the issue is related to subsequent requests to the same endpoint, not necessarily to headers. I haven't got a capacity to reproduce this, would you mind giving me a hand? If we can get a reliable reproduction repository where this issue occurs, we can track it down and find a solution.

**Comment by sean-hernon** [comment]
Hi @kettanaito yes I would certainly like to help when I get some free time.

In the case where no mocked response is returned, do you foresee that the issue will cause the real request to be corrupted? If two requests made to the same endpoint, but with different methods are issued, do you foresee any conflict there?

**Comment by sean-hernon** [comment]
I have tried to reproduce this issue, but have had no luck so far. Do you have any more information related to how you encountered the issue?

**Comment by kettanaito** [comment]
Thank you for assistance on this, @sean-hernon! Those insights are most useful. 

Please, if you happen to reproduce it, could you submit a pull request with a failing test that does so? It doesn't have to contain a solution straight away, as a reliable reproduction would help us find one much faster. Thanks.

**Comment by sean-hernon** [comment]
@kettanaito Do you remember what you did exactly to see the issue? Was it exactly as in the `steps to reproduce`?
