### ISSUE TITLE
ES Modules (node): named import of `request` doesn't get intercepted

### ISSUE THREAD

**Issue by lionralfs** [mswjs/interceptors#201]
Hey,

I'm using node version 16.6.2 along with ES Modules, which means I import node's native `https` lib like this:

```js
import { request } from 'https';

request('https://example.com/test', (res) => {})
```

However, requests are not intercepted when `request` is imported this way. The same behavior can be observed when doing this:

```js
import * as https from 'https';

https.request('https://example.com/test', (res) => {})
```

Here's a [repo](https://github.com/lionralfs/mswjs-interceptors-bug-repro) to show the complete code.

**Comment by kettanaito** [comment]
Thanks for reporting this, @lionralfs. This indeed looks off. It shouldn't matter how the `request` function is imported, it _references the same function_. 

Are you sure you're not using `node:https`?

**Comment by lionralfs** [comment]
Not sure what you mean by `node:https`, but I'm using node's built-in [https module](https://nodejs.org/api/https.html#httpsrequestoptions-callback).
As noted in my repo, requests are intercepted if the entire module is imported, and then used like this:

```js
import https from 'https';

https.request('...')
```

**Comment by kettanaito** [comment]
I was referring to the new way to import Node.js native modules:

```js
import { request } from 'node:https'
```

That's not the case for you, so my guess looks irrelevant. 

I've changed one of our integration tests for `https.request` to use the named import as you do. Could you take a look at https://github.com/mswjs/interceptors/pull/203 and see if it's different from your use case in any way? Requests are still intercepted in the test.

**Comment by lionralfs** [comment]
Hm, that's odd.
The only notable difference is the way I import the interceptor:

```js
import { interceptClientRequest } from '@mswjs/interceptors/lib/interceptors/ClientRequest/index.js';
```

The way you imported it in your tests before (`import * as https from 'https'`) also doesn't work for me:
https://github.com/lionralfs/mswjs-interceptors-bug-repro/blob/d93f27be924fec479adbcec06a14043ab7cbbb09/also-fails.js

Also note that I'm using `"type": "module"` in my package.json which makes node treat my '.js' files as ES Modules:
https://github.com/lionralfs/mswjs-interceptors-bug-repro/blob/d93f27be924fec479adbcec06a14043ab7cbbb09/package.json#L2

**Comment by kettanaito** [comment]
I think this has to do with what ESM does to named/default exports. What I've learned recently is that these two would yield totally different things in ESM:

```js
import * as http from 'http'
http.request

import { request } from 'http'
```

Those two `request` functions won't share their identity because ESM would do some magic with imports, converting them into an object or something (really not an ESM pro here, sorry). 

This is important because the Interceptors patch `http` with a specific import type:

https://github.com/mswjs/interceptors/blob/ddf0389c0a0f2f98350f3857d1e301f806c66587/src/interceptors/ClientRequest/index.ts#L1

I wonder if accounting for named imports would solve this issue:

```js
import http from 'http'
import { request } from 'http'

// do the patching
http.request = patch()
request = patch()
```

That should work but it'd be nice to have a failing test to begin with.

**Comment by richardm-stripe** [comment]
I found https://github.com/nock/nock/issues/2461 talking about `stripe-node`

**Comment by richardm-stripe** [comment]
Looks like https://github.com/mswjs/interceptors/issues/201 describes the same problem.
