### ISSUE TITLE
node 17.3 and `node-fetch`: requests intercepted twice

### ISSUE THREAD

**Issue by lionralfs** [mswjs/interceptors#205]
Hi,

I've noticed something rather odd: when using `node-fetch` and requests that have a request body either causes the request to be sent twice or being logged/intercepted twice. Note that this only happens in node versions >= 17.3.0. I'm not sure whether this is an issue with the interceptors or `node-fetch` itself. Here's the snippet I used to isolate the issue:

```js
import fetch from 'node-fetch';
import { createInterceptor } from '@mswjs/interceptors';
import nodeInterceptors from '@mswjs/interceptors/lib/presets/node.js';

const interceptor = createInterceptor({
  modules: nodeInterceptors.default,
  resolver(request, ref) {
    return {
      status: 200,
      body: JSON.stringify({
        success: true,
      }),
    };
  },
});

interceptor.apply();

interceptor.on('request', (request) => {
  console.log('[%s] %s', request.method, request.url.toString());
});

// node-fetch example taken from https://github.com/node-fetch/node-fetch#post-with-json
const body = { a: 1 };

fetch('https://httpbin.org/post', {
  method: 'POST',
  body: JSON.stringify(body),
  headers: { 'Content-Type': 'application/json' },
});
```

which logs (using `--trace-warnings`):

```
[POST] https://httpbin.org/post
[POST] https://httpbin.org/post
(node:91294) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessage]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at IncomingMessage.addListener (node:events:487:10)
    at IncomingMessage.Readable.on (node:internal/streams/readable:899:35)
    at IncomingMessage.once (node:events:531:8)
    at pipe (node:internal/streams/pipeline:321:9)
    at pipelineImpl (node:internal/streams/pipeline:293:9)
    at pipeline (node:internal/streams/pipeline:146:10)
    at NodeClientRequest.<anonymous> (<project_dir>/node_modules/node-fetch/src/index.js:248:15)
    at NodeClientRequest.emit (node:events:402:35)
    at NodeClientRequest.emit (<project_dir>/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js:288:46)
```

**Comment by lionralfs** [comment]
This might be an issue with node-fetch instead. Here's a bug report with the same error message: https://github.com/node-fetch/node-fetch/issues/1446

I've found that my example only throws the mentioned error in node `v17.3+` and node-fetch `v3.1.1+`

**Comment by jhillacre** [comment]
seeing this in node v18.12.1, with node-fetch 3.1.0 working but 3.1.1 & 3.3.0 doubling. the pr that is the reason for closing node-fetch/node-fetch#1446 (node-fetch/node-fetch#1474) was in 3.2.5, so it hasn't solved this issue.

**Comment by kettanaito** [comment]
There's been quite a lot of changes to the library over the past couple of months. Could someone please give this issue a reproduction on the latest interceptors version? 

We're also using Node 18 internally now and experience no double request interception. I'm tentative to consider this issue closed.

**Comment by lionralfs** [comment]
No issues with the latest release, closing this

**Comment by kettanaito** [comment]
@lionralfs, thanks for giving it a test. Glad to hear it's fixed.
