### ISSUE TITLE
What versions of node do we want to support?

### ISSUE THREAD

**Issue by trevoro** [mswjs/interceptors#217]
Hey,

Lots of the issues in this package seem to be related to the version of node that people are running. The test suite uses node v12 which lots of people have moved past at this point. If we can have a list of LTS releases that we want to support, then we can write the test suite in a way that supports all of them, then we can sort the issues out and bucket them. If anyone runs into a problem, we can just tag it with the version of node they're using and add the test, and that way we can have the library up to date for the known versions.

Here's an example of a test suite we could adopt for the versions that we want; essentially just loop through the different node versions. 

WDYT?

**Comment by kettanaito** [comment]
Hey, @trevoro. Thanks for raising this. 

It seems that a lot of recent issues are related to Node.js versions, just as you say. 

- https://github.com/mswjs/interceptors/issues/212
- https://github.com/mswjs/interceptors/issues/205
- https://github.com/mswjs/msw/issues/1125
- https://github.com/mswjs/msw/issues/1120
- https://github.com/mswjs/msw/issues/1113

I also agree that v12 is archaic and we must migrate from it. I suggest supporting LTS (16.14.0) as the base version. This means migrating all our packages to use that Node.js version, adjusting implementation, etc. I also have a suspicion that it was v16 that introduced at least some breaking changes, as I was able to reproduce a few issues on v16 and v17 with identical errors. 

I think that promising support of multiple Node.js versions would be quite a stretch, and suggest that we focus on LTS instead. This project doesn't have the manpower to support it as-is, bringing more Node.js versions support would only make things worse. 

If you've got a chance, I'd much appreciate your help with this! We can start by bumping the Node.js version in this repo and opening a pull request with just that. Let's see where the tests fail (if they do!).
