### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by lionralfs** [mswjs/interceptors#220]
Hey,

I couldn't find a license (apart from the package.json key) for this lib. It'd be great if you could add a LICENSE.md to the repo root.
Cheers.

**Comment by kettanaito** [comment]
## Released: v0.15.2 🎉

This has been released in v0.15.2!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.15.2)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.15.2)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
