### ISSUE TITLE
`getIncomingMessageBody` does not return on empty body

### ISSUE THREAD

**Issue by raon0211** [mswjs/interceptors#222]
Currently `getIncomingMessageBody` returns a promise, which is resolved when it reads data from the response. Unfortunately, when an HTTP response has no body, the promise is never resolved. 

https://github.com/mswjs/interceptors/blob/main/src%2Finterceptors%2FClientRequest%2Futils%2FgetIncomingMessageBody.ts#L8

**Comment by kettanaito** [comment]
Hi, @raon0211. This is a great catch. Thank you for reporting _and_ opening a pull request! I will look into it shortly.

**Comment by kettanaito** [comment]
## Released: v0.15.2 🎉

This has been released in v0.15.2!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.15.2)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.15.2)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
