### ISSUE TITLE
Documentation appears to be completely incorrect

### ISSUE THREAD

**Issue by lostfictions** [mswjs/interceptors#237]
Hi, thanks for this library! I'm trying to follow along with the README, but all the API definitions appear to be wrong.

This snippet:

```js
import { ClientRequestInterceptor } from '@mswjs/interceptors/lib/interceptors/ClientRequest'

const interceptor = new ClientRequestInterceptor()
interceptor.on('request', (request) => {
  // Introspect request or mock its response
  // via "request.respondWith()".
})
```

Doesn't appear to work: I receive the following error:

> Module '"@mswjs/interceptors/lib/interceptors/ClientRequest"' has no exported member 'ClientRequestInterceptor'.ts(2305)

This snippet:

```js
import { BatchInterceptor } from '@mswjs/interceptors'
import nodeInterceptors from '@mswjs/interceptors/lib/presets/node'

const interceptor = BatchInterceptor({
  interceptors: nodeInterceptors,
})

interceptor.on('request', (request) => {
  // Inspect the intercepted "request".
  // Optionally, return a mocked response.
})
```

Also doesn't work -- it appears `BatchInterceptor` is not part of the API anymore.

I've tried looking at the [releases](https://github.com/mswjs/interceptors/releases) to see if there was a breaking change that happened recently for which documentation wasn't updated, but I don't see anything describing a complete rewrite of the API on the first page.

Am I missing something obvious? Thanks!

**Comment by kettanaito** [comment]
Hey, @lostfictions. Sorry for the confusion.

The latest README features the latest API _that has not been releases yet_. I encourage you to select the correct Git tag in the GitHub's UI and browse the respective documentation.
