### ISSUE TITLE
🛑  0.15.2 TypeError: interceptors.createInterceptor is not a function

### ISSUE THREAD

**Issue by MarkLyck** [mswjs/interceptors#245]
It looks like a version 0.15.2 of this package was released about 4 hours ago.

After re-installing node_modules where I use `msw` I noticed this package was updated after my build and all of my unit and integration tests broke with the following error:

```
 FAIL  src/Routes/Dashboard/Dashboard.test.tsx [ src/Routes/Dashboard/Dashboard.test.tsx ]
TypeError: interceptors.createInterceptor is not a function
 ❯ Proxy.setupServer node_modules/.pnpm/msw@0.40.2_typescript@4.6.4/node_modules/msw/node/lib/index.js:8191:42
    8189|         }
    8190|         let resolvedOptions = {};
    8191|         const interceptor = interceptors.createInterceptor({
       |                                          ^
    8192|             modules: interceptors$1,
    8193|             resolver(request) {
 ❯ src/test/server.ts:5:15
 ❯ async src/test/setup.tsx:26:31
```

I tried manually installing version 0.15.1 and setting the resolution to 0.15.1 of this package, and my error was resolved.

It seems like there's a breaking change in 0.15.2.

If anyone else stumbles on this, downgrading this package to 0.15.1 fixed it for me.

**Comment by chentsulin** [comment]
@kettanaito v0.15.2 did a lot of changes to the codebase and public APIs. Should it be released as v0.16.0 instead?

ref: https://github.com/mswjs/interceptors/compare/v0.15.1...v0.15.2

**Comment by kettanaito** [comment]
Thanks for reporting this. Looks like I haven't named the refactor commit so it'd bump minor version. I will address this on Monday. For now, pin the dep to 0.15.1.

**Comment by kettanaito** [comment]
Okay, so I've got a chance to get to this sooner. 

- Re-published the 0.15.1 state as 0.15.3.
- Will release the actual next version as 0.16.0.

**Comment by philBrown** [comment]
https://semver.org/ ~ breaking changes should use a major version bump

**Comment by kettanaito** [comment]
@philBrown if you read the spec carefully enough, you will notice that breaking changes in pre-1.0 releases should, in fact, bump the _minor_ version. Hence the pre-1.0 with the ability to iterate faster.
