### ISSUE TITLE
Complete example for simple NodeJS response override

### ISSUE THREAD

**Issue by artur-michalak** [mswjs/interceptors#248]
Could you provide simple usage where request is overridden? I tried using respondWith method but without success. 
I know there is MSW with high level api, but for my use-case I'd prefer to write my own route matching mechanism.

Below you can check what i tried to do. Thanks for your help!

BTW. Docs are not up to date

```javascript
import nodeInterceptors from "@mswjs/interceptors/lib/presets/node";
import { BatchInterceptor } from "@mswjs/interceptors/lib/BatchInterceptor";

const interceptor = new BatchInterceptor({
  name: "test",
  interceptors: nodeInterceptors
});

interceptor.on("request", request => {
  if (request.url.toString() === "/example") {
    request.respondWith({
      status: 200,
      body: JSON.stringify({ data: "perfect" })
    });
  }
});

interceptor.apply();
```

**Comment by kettanaito** [comment]
Hey, @artur-michalak. 

I believe what you're doing in the example above should work. 

Here's an example of how to mock a response to an intercepted request:

https://github.com/mswjs/interceptors/blob/8040bb35d73e3a54c6e3e15c3c2d4e2f23e646a7/test/modules/http/response/http-https.test.ts#L19-L35

It uses `ClientRequestInterceptor` but you are likely to use `BatchInterceptor` instead, which has the same API in terms of "request" event handling. 

I agree it'd be useful to have a full example of response mocking in the README! Pull requests are always welcome. 

> BTW. Docs are not up to date

Oh, you're right, I think the required `name` has slipped through to the `BatchInterceptor`. If I recall correctly, that's only needed to name the internal logger. I may need to look into it and see if we need to expose it publicly.

**Comment by artur-michalak** [comment]
> Oh, you're right, I think the required `name` has slipped through to the `BatchInterceptor`. If I recall correctly, that's only needed to name the internal logger. I may need to look into it and see if we need to expose it publicly.

Well, there is little bit more ;) (import and missing new)
If you can confirm that my example is correct one then I'll do a PR 
```javascript
import { BatchInterceptor } from '@mswjs/interceptors'
import nodeInterceptors from '@mswjs/interceptors/lib/presets/node'

const interceptor = BatchInterceptor({
  interceptors: nodeInterceptors,
})

interceptor.on('request', (request) => {
  // Inspect the intercepted "request".
  // Optionally, return a mocked response.
})
```

**Comment by kettanaito** [comment]
I've rewritten the README sections to include the explanation and examples of how to [Introspect requests](https://github.com/mswjs/interceptors#introspecting-requests) and [Mock responses](https://github.com/mswjs/interceptors#mocking-responses). It now contains what you need.

**Comment by kettanaito** [comment]
I will also leave the `name` property of BatchInterceptor public for now. In the end, if you construct a batch of interceptors, give it a descriptive name so the logging is better (if you decide to log it with `DEBUG`). If this gets disruptive, I don't mind starting a discussion around removing it.
