### ISSUE TITLE
Could not find a declaration file for module 'debug'

### ISSUE THREAD

**Issue by Nargonath** [mswjs/interceptors#257]
I'm building a TS nodeJS project which uses:

* `typescript@4.5.4`
* `@mswjs/data@0.10.1`

But I have an error when I try to build the project:

```
node_modules/@mswjs/interceptors/lib/Interceptor.d.ts:1:26 - error TS7016: Could not find a declaration file for module 'debug'. '/projectFolder/node_modules/debug/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/debug` if it exists or add a new declaration (.d.ts) file containing `declare module 'debug';`

1 import { Debugger } from 'debug';
                           ~~~~~~~


Found 1 error.
```

Here is my `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2017",
    "noImplicitAny": true,
    "preserveConstEnums": true,
    "outDir": "./dist",
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}
```

Does `@mswjs/interceptors` need to add `@types/debug` to its devDep and export the definitions or is there a misconfiguration on my side?

For now I fix the issue by `npm i -D @types/debug` but I don't think I should have to install the types in my consumer project since I do not directly use `debug` but `@mswjs/data` does.

Thanks for your help and for the great library 💪 .

**Comment by kettanaito** [comment]
Hey, @Nargonath. Thanks for reporting this.

This is an issue and Interceptors should ship `@types/debug` as its regular dependency.

**Comment by kettanaito** [comment]
## Released: v0.17.3 🎉

This has been released in v0.17.3!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.17.3)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.17.3)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by kettanaito** [comment]
Hey, @Nargonath. I believe Data also doesn't consume it directly. It's a transient dependency:

```
data
  - msw
    - @mswjs/interceptors
```

Try re-installing your dependencies, and the latest Interceptors should be pulled in automatically.

**Comment by Nargonath** [comment]
Alright, perfect. Yeah I knew it was a transitive dependency but I didn't check the actual semver ranges in the respective `package.json`. Thank you again @kettanaito 🙏 .
