### ISSUE TITLE
One of integration test fails

### ISSUE THREAD

**Issue by 95th** [mswjs/interceptors#258]
I tried running `yarn test` and the below failure. Can you please help?

```
 FAIL  features/remote/remote.test.ts
  ● intercepts an HTTP request made in a child process

    thrown: 1

      37 | })
      38 |
    > 39 | test('intercepts an HTTP request made in a child process', async () => {
         | ^
      40 |   child.send('make:request')
      41 |
      42 |   const response = await new Promise((resolve, reject) => {

      at Object.<anonymous> (features/remote/remote.test.ts:39:1)
```

**Comment by kettanaito** [comment]
Hey, @95th. That's interesting. Is there any other error message above/below?

That test is for the remote interceptor, which means it spawns the actual test in a child process and uses IPC to communicate between the parent and the child processes to test the interception. Perhaps that fails in your case. 

Can you provide me more with the OS/node versions you're using?
