### ISSUE TITLE
Why don't the code examples in the README call `apply()`?

### ISSUE THREAD

**Issue by def-gthill** [mswjs/interceptors#278]
I was trying to use this library to intercept an HTTP response on a Node app. I followed the code examples in the README and was confused that nothing was being intercepted.

I was about to give up on the library as broken. Then I noticed that the interceptors have an `apply()` method. I added this to my code and got my intercepted responses!

Why don't the code examples in the README call `apply()`? Is it not always necessary? Is it just assumed that the user will somehow know to call it? It would be nice to have this clarified in the readme.

**Comment by kettanaito** [comment]
Hey, @def-gthill. Oh wow, what an oversight on my part. Those examples should use `.apply()` whenever they showcase the interception. There should be no assumptions when it comes to using it.

**Comment by def-gthill** [comment]
Awesome, thanks!

**Comment by kettanaito** [comment]
## Released: v0.17.4 🎉

This has been released in v0.17.4!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.17.4)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.17.4)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
