### ISSUE TITLE
Where is the source code for `page-with` and `@open-draft/test-server` packages?

### ISSUE THREAD

**Issue by milesrichardson** [mswjs/interceptors#282]
Hi, thanks for the great libraries!

I'm working on a PR to (hopefully) improve support for Node 18 and native fetch. So far I've found a few related bugs caused by incorrect serialization of IPv6 host in URLs, which is a problem on Node 18 when running in dual stack environments like GitHub Actions because `localhost` can resolve to `::1`, and some code in `page-with` and `test-server` libraries incorrectly serializes any IPv6 host to an invalid URL. The fix is to surround an IPv6 host with square brackets. 

This is an easy bug to fix, but I don't know where to make the PR. I haven't been able to find the source code for [`page-with`](https://www.npmjs.com/package/page-with) (no source listed) or [`@open-draft/test-server`](https://www.npmjs.com/package/@open-draft/test-server) (source link 404). Is the source code for these packages available somewhere? I see that @kettanaito is their maintainer, but I cannot find the source repositories on his profile nor anywhere in the mswjs organization.

In the meantime, I'm able to workaround the bug by fixing it with re-exports and prototype patching, but that's not ideal

**Comment by kettanaito** [comment]
Hey, @milesrichardson. 

Well, that's a mess. I'm glad to have this opportunity to clean things up. 

You can find the source code for `page-with` here: https://github.com/kettanaito/page-with. If you could also add the `repository` url in `package.json` as a part of your changes I'd be grateful! 

As for the `@open-draft/test-server`, it's a private package I've developed, so its source code is private for now. I don't have intention to open source it yet, but I can add the fix you propose manually and publish a new version so we can continue with proper testing of this, and many other dependent libraries.

On the related note, is the issue you're experiencing related to https://github.com/mswjs/interceptors/pull/215 by any chance?

**Comment by milesrichardson** [comment]
Thanks! I pushed my changes with the hacky patch version of these fixes in #283. I made sure the commits with the patches are atomic so that reverting them can be done with `git revert`. 

> You can find the source code for page-with here: https://github.com/kettanaito/page-with. If you could also add the repository url in package.json as a part of your changes I'd be grateful!

Cool, I will take a look at this and hopefully open a PR (probably should spend the next few hours on other priorities -_-)

Basically there are two issues: the version of `msw` needs to be upgraded (latest version fixes Node v18 and has no breaking changes on earlier versions AFAICT); and the IPv6 serialization needs to be fixed in `PreviewServer` and possibly other places that didn't surface bugs here.

> As for the @open-draft/test-server, it's a private package I've developed, so its source code is private for now. I don't have intention to open source it yet, but I can add the fix you propose manually and publish a new version so we can continue with proper testing of this, and many other dependent libraries.

Understood. The fix is simple here (same as `page-with` really) - you can see it in the PR. Unfortunately this is the package I had to patch by mutating its prototype and re-exporting it, which meant I needed to update the import of every file that uses `@opendraft/test-server`. This makes the PR dirty, but at least it's an easy revert.

> On the related note, is the issue you're experiencing related to https://github.com/mswjs/interceptors/pull/215 by any chance?

Yes, I think this is one of the issues I fixed, but that change alone did not fix all the issues for some reason, I can't remember exactly why, but you can see the various fixes in the commits which are all related to IPv6 handling, except for the one that was incorrectly accessing `URL.url` instead of `URL.href`.

**Comment by milesrichardson** [comment]
@kettanaito I fixed the upstream `page-with` bug in https://github.com/kettanaito/page-with/pull/9

Once that's fixed and released, I can update #283 to use the new `page-with` dependency, although that could be merged regardless (since it has the patch fix). 

I'll close this issue since the question was answered. Thanks for open sourcing `page-with`, and for taking a look at `@opendraft/test-server` (the fix for which you can copy from #283).

**Comment by kettanaito** [comment]
Thank you for your involvement, @milesrichardson! It's my pleasure to review pull requests like this one.
