### ISSUE TITLE
How to read form data from intercepted request?

### ISSUE THREAD

**Issue by cliffordfajardo** [mswjs/interceptors#289]
Given an interceptted request that is submitted with form data (has a header of `'content-type': 'application/x-www-form-urlencoded'`) how would I extract the form data from the [InteractiveIsomorphicRequest](https://github.com/mswjs/interceptors/blob/e305d3815851dbdfd674e2b412f2c2e0288fc1de/src/IsomorphicRequest.ts)?

## Related
- https://github.com/mswjs/interceptors/issues/288
- https://github.com/mswjs/msw/issues/1404

**Comment by kettanaito** [comment]
This is not currently possible. Node internals don't expose any means to read that data either: for them it's just a buffer with content-encoding that the consumer must treat as it wishes. 

I don't think we're going to implement this, to be honest. I'd much more prefer to use us migrating to the `Request`/`Response` polyfill from Remix where those methods are implemented.
