### ISSUE TITLE
TypeError: interceptors.map is not a function

### ISSUE THREAD

**Issue by vismodo** [mswjs/interceptors#293]
I used this code and it threw an error

```js
const { RequestInterceptor } = require('node-request-interceptor')
const withDefaultInterceptors = require('node-request-interceptor/lib/presets/default')

const interceptor = new RequestInterceptor(withDefaultInterceptors)
```

Node says that `const interceptor = new RequestInterceptor(withDefaultInterceptors)` threw the error

**Comment by kettanaito** [comment]
Hey, @vismodo. Not sure what you're trying to do but that example doesn't look correct: there's no `RequestInterceptor` export from this library. 

If you want to combine multiple interceptors, you must use `BatchInterceptor` as described in the docs:

https://github.com/mswjs/interceptors#presets

> We export the `Interceptor` class but it's an abstract class that every interceptor needs to implement. You likely don't need it at all for your use case unless you're building a custom interceptor (which you, probably, shouldn't do in the first place).

**Comment by kettanaito** [comment]
@vismodo that's the old version of the package. Please, always check the package version vs the latest published version on GitHub. That package has been discontinued for years (no such thing as "unpubilsh a package" in NPM).
