### ISSUE TITLE
Guidance on using BatchInterceptor - how to inspect body

### ISSUE THREAD

**Issue by john-maddock** [mswjs/interceptors#294]
I'm using BatchInterceptor and trying to inspect the body of a fetch response in the browser
I didnt see an example so took the example in ClientRequestInterceptor as inspiration

```
interceptor.on("response", (response, request) => {
    const url = new URL(response.url);

    if (url.origin.includes("localhost")) {
        console.log(
            response
        );
    }
});

```

when i run it and intercept the response i see the body json in the request(second) arg..

![image](https://user-images.githubusercontent.com/9953144/196443705-70a1e3d2-e113-4a69-87fa-16cc7fb13467.png)

Is this the expected way to get it ?.. just want to be sure im using it correctly

**Comment by kettanaito** [comment]
Hey, @john-maddock. 

That appears to be correct. As of now, `response.body` will be a string representation of the response body. 

Note that I'm almost done with the breaking change regarding how this library treats requests and responses in #292. Once that change is merged, you will be able to work with the response as Fetch API Response. This means you'll get its `ReadableStream` body and will be able to read it as `.text()`, `.json()`, `.arrayBuffer()` and so forth.

**Comment by john-maddock** [comment]
@kettanaito  thanks so much for your quick reply
