### ISSUE TITLE
TypeError: this.agent.destroy is not a function

### ISSUE THREAD

**Issue by Y2zz** [mswjs/interceptors#304]
I am using Vitest to run the test, when I intercept the   [request.js](https://github.com/request/request) requests, the program issues an error message

vitest: `0.25.2`
request.js: `2.28.2`
msw: `0.48.3`

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: this.agent.destroy is not a function
 ❯ NodeClientRequest.terminate node_modules/msw/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:361:16
 ❯ NodeClientRequest.respondWith node_modules/msw/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:353:10
 ❯ node_modules/msw/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:164:14
 ❯ processTicksAndRejections node:internal/process/task_queues:95:5
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

```

**Comment by kettanaito** [comment]
Hey, @Y2zz. Thanks for reporting this.

Which version of Node.js are you running? I suppose it's 17-18. Looks like somewhere along the versions Node removes `HttpAgent.prototype.destroy` which we rely on when finishing up the intercepted request. If you could confirm the Node version that'd be great.

**Comment by kettanaito** [comment]
I've looked into Node docs and `HttpAgent.prototype.destory` certainly hasn't gone anywhere:

- https://nodejs.org/docs/latest-v16.x/api/http.html#agentdestroy
- https://nodejs.org/docs/latest-v17.x/api/http.html#agentdestroy
- https://nodejs.org/docs/latest-v18.x/api/http.html#agentdestroy

The issue must have to do with `request.js` specifically. It's not uncommon for third-party libraries to misused Node primitives for one reason or another, and we've encountered quite a number of issues around this.

**Comment by kettanaito** [comment]
[request.js](https://github.com/request/request) seems to be officially deprecated, with the last update done 4 years ago. This means that request.js has no support for Node 14 and is using older versions of node, which this library doesn't support. We support only Node 14+.

**Comment by Lord-Kamina** [comment]
@kettanaito I am experiencing this same error, not related to `request.js` (reported it over at the msw repo in https://github.com/mswjs/msw/issues/1515) while trying to intercept OctoKit requests.

**Comment by kettanaito** [comment]
@Lord-Kamina, that's really odd. I believe Node's `http` module always creates an HTTP agent and uses it to handle requests (hence, the `http.defaultAgent`). I don't recall if you can opt-out from this behavior. Maybe that's what's happening. 

The fix itself is rather trivial: don't rely on `this.agent` always being defined. But before we do that, we need to know for sure what are the cases agent may not be defined.

**Comment by Lord-Kamina** [comment]
> @Lord-Kamina, that's really odd. I believe Node's `http` module always creates an HTTP agent and uses it to handle requests (hence, the `http.defaultAgent`). I don't recall if you can opt-out from this behavior. Maybe that's what's happening. 
> 
> 
> 
> The fix itself is rather trivial: don't rely on `this.agent` always being defined. But before we do that, we need to know for sure what are the cases agent may not be defined.

I noticed my version of node should be supported, but was still a bit old (16.18); I tried updating to 19.4 and the issue no longer occurs, so I guess it's version dependent?

**Comment by kettanaito** [comment]
@Lord-Kamina, honestly, no idea. I haven't even tested the ecosystem on Node 19 and we don't have official support for Node 18, to begin with. But whatever solves the issue, I'm glad.

**Comment by Lord-Kamina** [comment]
@kettanaito it was a premature celebration after all... the interceptor is apparently not doing anything at all in v19, which would explain it not throwing either.

**Comment by Lord-Kamina** [comment]
@kettanaito It's apparently an issue with OctoKit. Taking a gander at their source code, I found this:

```typescript
  return fetch(
    requestOptions.url,
    Object.assign(
      {
        method: requestOptions.method,
        body: requestOptions.body,
        headers: requestOptions.headers as HeadersInit,
        redirect: requestOptions.redirect,
      },
      // `requestOptions.request.agent` type is incompatible
      // see https://github.com/octokit/types.ts/pull/264
      requestOptions.request as any
    )
  )
...
```

**Comment by kettanaito** [comment]
Well, isn't that another story from the Nodeland. The worst part is that we need to handle scenarios like this because when things go South people will blame MSW, and not the incorrect usage of Node API in their request client.

**Comment by Lord-Kamina** [comment]
> Well, isn't that another story from the Nodeland. The worst part is that we need to handle scenarios like this because when things go South people will blame MSW, and not the incorrect usage of Node API in their request client.

Figures. I have no idea (nor do I care to find out, honestly) why are they doing that.

**Comment by kettanaito** [comment]
@Lord-Kamina, please, would you be interested in opening a pull request in this repo? Making that `this.agent.destroy()` call in NodeClientRequest module conditional?

**Comment by kettanaito** [comment]
## Released: v0.19.4 🎉

This has been released in v0.19.4!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.19.4)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.19.4)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by markfranco** [comment]
Hi there,

I've seen that this has been closed and merged, but it's still an issue for me when using the `msw` package.

Even though the latest version for the interceptors package is `0.22.12`, when downloading the latest `msw` at `1.2.1`, it still only gets `0.17.9`, even though there are newer versions available.

I'm wondering if it is this lock file https://github.com/mswjs/msw/blob/main/pnpm-lock.yaml#L77 that keeps downloading `0.17.9`.

**Comment by kettanaito** [comment]
@markfranco, thanks for letting me know. The versions are correct, MSW is not yet on the latest Interceptors because those work via the Fetch API already. I may try backporting this into the latest compatible release.

**Comment by markfranco** [comment]
Great! 👍🏽 Alright then, I'll keep an eye out for it then, and thanks again for all the great work 👏🏽

**Comment by freben** [comment]
As per the above PR, this keeps happening to us, randomly, in particular in one special test. https://github.com/backstage/backstage/actions/runs/9581427428/job/26418304820?pr=25302 But only in CI; haven't had it happen locally even once yet.

I'm tempted to make an even more defensive PR than https://github.com/mswjs/interceptors/pull/330, along the lines of

```ts
const destroy = this.agent?.destroy;
if (typeof destroy === 'function') {
  destroy();
}
```
