### ISSUE TITLE
Add "requestException" event

### ISSUE THREAD

**Issue by smo043** [mswjs/interceptors#307]
Hello Team,

I don't find a discussion channel, therefore I'd like to ask a couple of queries about this library; please advise.

- Can we use this library in production as a replacement for Axios interceptors, or is it solely for unit tests?
- I only see `interceptor.on('request'), interceptor.on('response')`. Is there a method to catch API request and response errors?

Thanks

**Comment by kettanaito** [comment]
Hey, @smo043. 

> Can we use this library in production as a replacement for Axios interceptors, or is it solely for unit tests?

This library is a low-level HTTP request interception library. You can use it anywhere in any way that employs request interception. It is a replacement for Axios interceptor, and it can intercept any requests from any request clients, not just Axios.

I'm a bit cautious why would you use request interceptor in _production_ though. Maybe if you share your use case I can provide a more relevant answer here. 

> I only see `interceptor.on('request')`, `interceptor.on('response')`. Is there a method to catch API request and response errors?

There is no API to react to request errors (i.e. malformed requests).

Response errors are somewhat irrelevant in this context of request interception as it's the server that's aware of them. What you can react to is _error responses_, as those are still valid responses you receive in the "response" event.

**Comment by kettanaito** [comment]
I believe you should be able to use this library for this kind of logging. It may be future incomplete, however, to suit all the requirements.

For once, we don't forward any request errors to the consumer at the moment. I think this would be a good addition to our API. We control request modules so we know when request errors happen:

https://github.com/mswjs/interceptors/blob/ddf0389c0a0f2f98350f3857d1e301f806c66587/src/interceptors/ClientRequest/NodeClientRequest.ts#L185

Should be a matter of introducing a new event alongside "request" and "response". Maybe something like "requestError" or "requestException"? In either case, I'm for supporting this.

**Comment by smo043** [comment]
@kettanaito - Thank you, would it be possible to have a minor release by exposing the `reqException` and `resException` similar to what Axios interceptor has?

**Comment by kettanaito** [comment]
Yeah, sure. 

I don't know about the `resException` though. I said above that response exceptions are unknown to the client, the same way you have no ways to know if an exception happened on the server unless it sends a 5xx response indicating that. I see little reason for something like `resException`, given you already have a `response` event which you can listen and react to error responses:
```js
interceptor.on('response', (response) => {
  if (response.status === 500) {
    resException()
  }
})
```

**Comment by smo043** [comment]
Thank you, I was thinking about the same about the res exception. It would be very helpful if you could release a minor version for the request exceptions. Appreciate your assistance.

**Comment by kettanaito** [comment]
It's not on my priority list as I'm working on some major changes in MSW right now, and plan on focusing on those until the end of the year. I can look into this whenever I have time, otherwise it's a pretty good first issue for new contributors.

**Comment by kettanaito** [comment]
@smo043, hey. Thanks for reporting that. It does seem like an issue but it should be relatively easy to fix it. Could you please open a new issue for it? Thanks.

**Comment by smo043** [comment]
> @smo043, hey. Thanks for reporting that. It does seem like an issue but it should be relatively easy to fix it. Could you please open a new issue for it? Thanks. 

Sure
