### ISSUE TITLE
Remove logs

### ISSUE THREAD

**Issue by ArielGueta** [mswjs/interceptors#320]
Hi,

How can I disable the logs? I'm seeing logs from `fetch/index.js` file

```ts
 console.log('or req headers', Array.from(request.headers.entries()));
```

I'm on version 0.19.0

Thanks.

**Comment by kettanaito** [comment]
Hey. This has been fixed in https://github.com/mswjs/interceptors/commit/3993619e8969408295e3d5ab538668b80f4a2115 but wasn't flagged as a `fix` so it never triggered an automated release. I will make a new release with this.

**Comment by kettanaito** [comment]
Published in https://github.com/mswjs/interceptors/releases/tag/v0.19.1
