### ISSUE TITLE
XHR `loadend` event may be too late for interception finalization

### ISSUE THREAD

**Issue by blaenk** [mswjs/interceptors#321]
Curious if my analysis here is correct. I tried this change locally and it appeared to work for this specific use case but bringing this up for discussion in case I'm misunderstanding something or taking the wrong approach. I'll file a tentative PR soon.

I've been debugging and stepping-through a site that I'm intercepting with this package using a chrome extension to inject my code into the same execution context as the page. To be clear: this strategy does work and I've used it successfully with this same package, it's just that the site is in the process of rolling out a new design/version which is giving me some issues.

Anyway, I _believe_ that I've arrived at the issue (aside from #318 which was also an issue).

It appears that the website has an `onload` event handler for a GraphQL fetcher which essentially checks the `xhr.status`:

```javascript
s.onload = function() {
    var n = {
        status: s.status,
        statusText: s.statusText,
        headers: b(s.getAllResponseHeaders() || "")
    };
    n.url = "responseURL"in s ? s.responseURL : n.headers.get("X-Request-URL");
    var e = "response"in s ? s.response : s.responseText;
    r(new E(e,n))
}
```

Pardon the pretty-printed minified code, this is a website I have no control over.

In the code above, `E`'s constructor is this:

```javascript
function E(n, e) {
    e || (e = {}),
    this.type = "default",
    this.status = void 0 === e.status ? 200 : e.status,
    this.ok = this.status >= 200 && this.status < 300,
    this.statusText = "statusText"in e ? e.statusText : "OK",
    this.headers = new d(e.headers),
    this.url = e.url || "",
    this._initBody(n)
}
```

So note `this.ok` is based on the `xhr.status`. However, at this point, `xhr.status` is `0` according to the debugger. This is causing the higher-level GraphQL code to believe that every request is failing.

If I'm understanding correctly, it seems like this library "finalizes" the intercepted request, wiring in the `.status` field and so on, only at `loadend`:

https://github.com/mswjs/interceptors/blob/3c0b5ec1995b76b6bceb88c08177b4d3654a3995/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L432-L456

Maybe the reason for doing this was because this single handler can handle both success and failure. Unfortunately it seems to mean that the underlying interceptor-unaware code may try to access e.g. the `.status` field in `load` or `error`, which won't be set since `loadend` runs only after that event?

If my analysis is correct, it seems one option might be to factor the finalization code out into a function and call it in handlers for both `load` and `error`. If so, not sure if this should also be done for `abort` and `timeout`.

MDN [appears to confirm](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#events) that `loadend` runs only after these other events:

> Fired when a request has completed, whether successfully (after [load](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/load_event)) or unsuccessfully (after [abort](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort_event) or [error](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/error_event)). Also available via the onloadend event handler property.

Alternatively it occurred to me, if the analysis is correct, that it might be done in a single location in `readystatechange` when `originalRequest.readyState === XMLHttpRequest.DONE` but I have no clue if that's correct. The [spec](https://xhr.spec.whatwg.org/#dom-xmlhttprequest-readystate) appears to say that `DONE` is emitted for success and any kind of error as well. MDN [appears to corroborate this](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState). The existence of https://github.com/mswjs/interceptors/issues/103 means that the finalization code would need some kind of `isFinalized` variable to avoid running it twice (may be worth doing anyway 🤷🏼‍♂️).

**Comment by kettanaito** [comment]
## Released: v0.19.3 🎉

This has been released in v0.19.3!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.19.3)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.19.3)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
