### ISSUE TITLE
How to catch errors thrown by the interceptor?

### ISSUE THREAD

**Issue by WesleyYue** [mswjs/interceptors#325]
Our use case for the interceptor is to log outgoing HTTP requests/responses. Since this is not a critical feature, we don't want any errors thrown by interceptor to crash the whole stack. Currently, we're running into an error with the new Fetch API explicitly banning body in GET requests (something that's not in the HTTP spec, and that lots of existing external libraries, like Stripe or elasticsearch, does).

The stack trace looks like this:
```
>  /src/node_modules/@remix-run/web-fetch/src/request.js:95
>  			throw new TypeError('Request with GET/HEAD method cannot have body');
>           ^
>  TypeError: Request with GET/HEAD method cannot have body
>      at new Request (/src/node_modules/@remix-run/web-fetch/src/request.js:95:10)
>      at new RequestOverride (/src/node_modules/@mswjs/interceptors/src/utils/RequestWithCredentials.ts:12:19)
>      at createRequest (/src/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/utils/createRequest.ts:26:10)
>      at NodeClientRequest.end (/src/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:136:42)
>      at NodeClientRequest.<anonymous> (/src/node_modules/stripe/lib/net/NodeHttpClient.js:68:15)
>      at Object.onceWrapper (node:events:628:26)
>      at NodeClientRequest.emit (node:events:525:35)
>      at NodeClientRequest.emit (/src/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:289:22)
```

Since this is outside the definition of the .on() callbacks, is there a way that we can catch any errors thrown by interceptor and log them as warnings instead?

**Comment by kettanaito** [comment]
Hi. I looked into this and provided some insights in https://github.com/mswjs/msw/discussions/1464#discussioncomment-4490409. There's no way to perform a HEAD/GET request in Node.js and in the browser by any means.

I do suspect you're doing something wrong here. Feel free to provide more context on this, include the request code, and show some examples of how Stripe/others ask you to perform a GET request with a body.

**Comment by kettanaito** [comment]
> Since this is outside the definition of the .on() callbacks, is there a way that we can catch any errors thrown by interceptor and log them as warnings instead?

No. This library does not alter nor give you the means to alter request/response errors. If it did, it'd compromise the integrity of the requests, which is not the goal. In your case, this is an exception thrown by the request module, not the interceptor, and it must remain as an exception otherwise we'll be creating an illusion that things works fine while using this library while they will fail if you deactivate it.
