### ISSUE TITLE
Drop web-encoding dependency

### ISSUE THREAD

**Issue by stefnotch** [mswjs/interceptors#332]
The web-encoding dependency seems to no longer be needed, since `TextEncoder` and `TextDecoder` are supported in all maintained Node.js versions and browsers.

This would also have the advantage of no longer having an indirect dependency on a rather heavyweight package: https://www.npmjs.com/package/util

**Comment by kettanaito** [comment]
Hey, @stefnotch.

While `TextEncoder` API is generally available in the browser and in Node, certain tools, like Jest, explicitly opt-out of all globals and then introduce them manually. For instance, you won't be able to execute code that relies on `TextEncoder` in Jest 26 (may also be the case of v27 and 28 as Jest is notoriously strict about including well-established Node globals into its environment for, well, reasons, I assume). 

This is the primary reason why we still rely on `web-encoding`. 

> This would also have the advantage of no longer having an indirect dependency on a rather heavyweight package: https://www.npmjs.com/package/util

That's a nice find. I thought `web-encoding` relies on native `util` module from Node but it seems to be an [explicit dependency](https://github.com/Gozala/web-encoding/blob/7197c998ca9dba0e2e9aec675f5897e541593d95/package.json#L39-L41). That being said, Interceptors and MSW are development tools, so we can ignore the dependency price in pretty much every situation unless it directly affects the tool's performance. I don't believe that having `util` as a transitive dependency has any negative effect on the users' performance. 

## Next steps

Would you have a minute to check if you can import `TextEncoder` in Jest 28-29? If you can, and they have finally included that global, I may be for dropping `web-encoding` alongside older Jest versions and moving to the brighter future.

**Comment by stefnotch** [comment]
Okay, I followed the Jest getting started https://jestjs.io/docs/getting-started , tweaked it to create a `let x = new TextEncoder();` and use it `expect(x.encode("cat")[0]).toBe(99);`.

 Then tested it with a few versions:
- `"jest": "=26.6.3"`:  TextEncoder is not defined
- `"jest": "=27.5.1"`: works
- `"jest": "^28.1.3"`: works
- `"jest": "^29.4.1"`: also works, so that's nice

It seems to have been added to Jest's Node.js environment here https://github.com/facebook/jest/pull/8022

However, it does not work when using it with the jsdom environment (which is apparently its own jest-environment-jsdom package, starting from Jest v28). The issue for that is https://github.com/jsdom/jsdom/issues/2524 , which I think depends on https://github.com/jsdom/whatwg-encoding/pull/11

**Comment by kettanaito** [comment]
Thank you so much for testing that!

That is such a shame that jsdom environment excludes the native `TextEncoder` API. That's the blocker for us, because once we drop `web-encoding` and start relying on globals, everybody who uses MSW in Jest (and jsdom, which is the majority of our users) will have their tests failing. They will see MSW using `TextEncoder` that is undefined, and immediately assume it's a problem with the library when it's actually a very strange behavior from Jest to say the least. 

Unless https://github.com/jsdom/jsdom/issues/2524 is resolved, we cannot rely on the platform, as sad as it sounds.
