### ISSUE TITLE
Implement Proxy-based ClientRequest interception

### ISSUE THREAD

**Issue by kettanaito** [mswjs/interceptors#346]
The current implementation also causes race condition issues since we're running in parallel with the native `end()` (we're extending). 

- XMLHttpRequest reference: #337

**Comment by kettanaito** [comment]
We already have primitives for a bit less verbose proxying with the `createProxy()` function. Should use that for this implementation as well.

**Comment by detj** [comment]
ow! I had assumed this was implemented using [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). Then I looked into the code and found only the XMLHttpRequestController implementation is based on Proxy.

Proxy for `fetch` would be fantastic!

**Comment by kettanaito** [comment]
Largely irrelevant now. See #515.
