### ISSUE TITLE
React Native "Unable to resolve module http" (Advise needed)

### ISSUE THREAD

**Issue by RNEvok** [mswjs/interceptors#362]
Hello guys. Thank you for awesome lib! It works fine in my Node.js project. But I wonder, is there any instruction how to use it with RN? Currently, I am getting error: "Unable to resolve module http" when trying to use ClientRequestInterceptor.

Reading other issues, I understood that RN support is offered. Maybe there is special branch for RN or something?

p.s. Only FetchInterceptor works fine but I need Interceptor that sees http.request(s)

RN version: 0.66.4
<img width="344" alt="Снимок экрана 2023-03-10 в 02 46 13" src="https://user-images.githubusercontent.com/81921589/224186094-e36ab45d-f8ae-4fe3-9576-3677fcb8db0d.png">

**Comment by kettanaito** [comment]
Hey, @RNEvok. Thanks for raising this. 

I believe that React Native doesn't have the standard `http` module. What you may be using only has a compatible signature but is implemented by other means. 

MSW ships with only `XMLHttpRequestInterceptor` for React Native and it seems to be covering the use cases people want. Try that interceptor instead, I suspect `http` may be implemented by XHR in React Native. 

Please let me know if that helps.

**Comment by RNEvok** [comment]
> 

Just tried XMLHttpRequestInterceptor. I am getting this error: "TypeError: Cannot read property 'prototype' of undefined, js engine: hermes". Currently I am trying to get more information of this error. Starting project with xCode did not gave me any additional information.

The code i am trying to run: 
`
import { XMLHttpRequestInterceptor } from '@mswjs/interceptors/XMLHttpRequest';

const interceptor = new XMLHttpRequestInterceptor();

interceptor.apply()

interceptor.on('request', (request, requestId) => {
  console.log(request.method, request.url)
})

interceptor.on('response', (response, request) => {
  console.log('response to %s %s was:', request.method, request.url, response)
})
`
![2023-03-10 19 49 20](https://user-images.githubusercontent.com/81921589/224374647-c561cb23-825e-46eb-8afc-3a8c31ad6937.jpg)

I'll try to get more information of this error and I'll edit comment if I know anything.

**Comment by kettanaito** [comment]
Sorry, I don't have enough insight into React Native to advise here.

Perhaps take a look at the RN usage example one of our contributors prepared https://github.com/mswjs/examples/pull/60 maybe you will find a missing piece there.
