### ISSUE TITLE
Patched `fetch` interceptor errors when passing URL instance on node 20

### ISSUE THREAD

**Issue by rossipedia** [mswjs/interceptors#386]
When using a string as the first argument to `fetch()`, all is well.

When passing a `new URL()` instance, an error is thrown.

<img width="860" alt="Screenshot 2023-06-25 at 3 54 55 PM" src="https://github.com/mswjs/interceptors/assets/96213/4ad5d7a0-1d99-47fe-8bac-abb680efbe6a">

**Comment by kettanaito** [comment]
Hi, @rossipedia. Thanks for letting me know.

Could you try this on `msw@next`? This looks like something we've fixed there.
