### ISSUE TITLE
Handle errors in the interceptor handler

### ISSUE THREAD

**Issue by mikicho** [mswjs/interceptors#437]
Following [this comment](https://github.com/nock/nock/pull/2517#issuecomment-1728463028).

Problem: [this line](https://github.com/mswjs/interceptors/blob/b8bce893d7e9642a9836ad29a0903562dde7fbca/src/interceptors/ClientRequest/NodeClientRequest.ts#L195) throws when an error occurs in the handler.
This prevents the user from handling errors with `error` listener in the request, which causes [this test ](https://github.com/nock/nock/blob/main/tests/test_intercept.js#L363) to fail.

I think it's because we currently don't `catch` [the promise](https://github.com/mswjs/interceptors/blob/b8bce893d7e9642a9836ad29a0903562dde7fbca/src/interceptors/ClientRequest/NodeClientRequest.ts#L206), we only handle the `then` case.

**Comment by kettanaito** [comment]
Hi. Have you tried using `Response.error()` instead of throwing in the request listener? 

`until()` works as try/catch so exceptions in its closure will also propagate to the `.then()` callback as `result.error`.

**Comment by mikicho** [comment]
> Hi. Have you tried using Response.error() instead of throwing in the request listener?

Yes, it converts the error to a generic Network error, which is not what we are after.

> until() works as try/catch so exceptions in its closure will also propagate to the .then() callback as result.error.

Interesting, this is not what see, the code never gets to the `then` clause, I'll try to reproduce it in a small script without Nock's noise.

**Comment by mikicho** [comment]
Update: in seems like it's working as expected when I isolated the scenario in a small script.
I'll keep updating my findings and close this ticket if needed.

**Comment by mikicho** [comment]
My mistake. 
For reference, if you use a `promise`, reject it instead of throw an error:
```js
interceptor.on('request', function ({ request: mswRequest, requestId }) {
  const request = mswRequest.clone()
  return new Promise((resolve, reject) => {
     throw error; // not working
     reject(error) // good
  })
}); 
```
