### ISSUE TITLE
Propagate socket error event on res.destroy

### ISSUE THREAD

**Issue by mikicho** [mswjs/interceptors#449]
[According to docs](https://nodejs.org/api/http.html#messagedestroyerror), `response.destroy(err)` emits `error` event.:

> If error is provided, an 'error' event is emitted on the socket and error is passed as an argument to any listeners on the event.

https://github.com/nodejs/node/blob/main/lib/internal/streams/destroy.js#L136

--- 
Nock [handles ](https://github.com/nock/nock/blob/feaa66fa64d24f95937ef759cdd5a7ca07646f1c/lib/intercepted_request_router.js#L125) this by overriding the Socket class and propagate the event to the request.

@kettanaito 
I tried to open a PR for this but couldn't understand how to do this, but I believe I'll be able to with your direction.

**Comment by mikicho** [comment]
Update: the response behavior isn't identical to the original response. `IncomingMessage` and `PassThrough` act differently on `destroy`

**Comment by mikicho** [comment]
@kettanaito Why do we skip properties if they have the same name? The implementation may be still different 
If I delete [these lines](https://github.com/mswjs/interceptors/blob/main/src/interceptors/ClientRequest/utils/cloneIncomingMessage.ts#L63-L65) my test passes because it calls to the correct implementation.

**Comment by kettanaito** [comment]
## Released: v0.32.1 🎉

This has been released in v0.32.1!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.32.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.32.1)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
