### ISSUE TITLE
should call callback before response event

### ISSUE THREAD

**Issue by mikicho** [mswjs/interceptors#459]
Node.js behaviour:
```js
const http = require('http');

const req = http.get('http://nowhere.com/', res => {
  console.log('response event');
})
req.on('finish', () => console.log('finish'))
req.end('', null, () => console.log('callback'))
```
This prints:
> finish
> callback
> response event

Mocked behavior:

```js
const { ClientRequestInterceptor } = require('@mswjs/interceptors/ClientRequest')
const http = require('http');

const interceptor = new ClientRequestInterceptor({
  name: 'my-interceptor',
})
interceptor.apply();
interceptor.on('request', async ({request}) => {
  request.respondWith(new Response())
});

const req = http.request('http://nowhere.com/', res => {
  console.log('response event');
})
req.on('finish', () => console.log('finish'))
req.end('', null, () => console.log('callback'))
```

Prints:
> finish
response event
callback

I can open a PR that pass the [callback](https://github.com/mswjs/interceptors/blob/122a6533ce57d551dc3b59b3bb43a39026989b70/src/interceptors/ClientRequest/NodeClientRequest.ts#L324) to the `respondWIth` and put it after the [finish event](https://github.com/mswjs/interceptors/blob/122a6533ce57d551dc3b59b3bb43a39026989b70/src/interceptors/ClientRequest/NodeClientRequest.ts#L500).

**Comment by kettanaito** [comment]
Hi, @mikicho. Can you please describe the expected behavior here? Is this the callback order that you find wrong? That seems to be correct (in your example). Are we not printing some of this? I suppose the `.end()` callback never gets called for bypassed requests?

**Comment by mikicho** [comment]
Sorry for the incomplete description. Updated it.
