### ISSUE TITLE
Simplify the npm package files

### ISSUE THREAD

**Issue by tkrotoff** [mswjs/interceptors#572]
The generated npm package contains files that are randomly named like chunk-GUY7XK43.mjs. Please make the npm package files human friendly.

This makes the source code difficult to debug (in the context of an application that uses @mswjs/interceptors via node_modules).

I had a hard time finding a performance issue with JSDOM because of this: https://github.com/tkrotoff/jsdom-slow-URL-parsing

<img width="231" alt="image" src="https://github.com/mswjs/interceptors/assets/643434/c4f8ddfb-5a8e-4b1e-bada-eca49af7b511">

**Comment by kettanaito** [comment]
Hi, @tkrotoff. Thanks for raising this. 

What chunk format would you consider more friendly? 

Note, these are automatically generated by `tsup`. We can change the chunk name pattern but they will always be named somewhat randomly (right now it's based off the chunk's hash). The chunks are also correctly split since you want granular modules to have granular imports in ESM. 

If you can tell me more about the issue you've experienced, the way you tried to debug, and the way that actually worked, that would help me in making the right decision here. Thanks.

**Comment by tkrotoff** [comment]
> What chunk format would you consider more friendly?

No chunks

> tsup

I've never used tsup nor needed it for my libraries, maybe it's not a great tool, maybe you don't need it.

For example, you don't need to ship the .map files (source maps): you don't need to minify the code and Node.js knows recent ES features so the original code and the bundled code are almost identical.
You also don't need to ship the original TypeScript source code.

> the way you tried to debug

You have a performance issue (https://github.com/tkrotoff/jsdom-slow-URL-parsing).
You put console.log, console.time, IDE breakpoints in your code + in node_modules to understand what's going on.
Having multiple files (in node_modules) named randomly with indirections makes it hard and error-prone.

**Comment by kettanaito** [comment]
> No chunks

That's now how ESM works. Your test will end up importing everything and evaluating everything, which will make it slow. Not to mention there are parts of this library meant only for Node.js, while others are meant for Node.js/browser (mixed) environments. 

> I've never used tsup nor needed it for my libraries

Sounds like you have a familiarity bias then. I've been using tsup for years, and now plenty of projects that do the same. Perhaps you never happened to ship libraries in the formats I need to ship them. 

> You have a performance issue

If URL paring is slow in <insert environment here>, that is no shape or form an issue with this library. I don't see how this is relevant here. 

## Conslusion

This library has no issues with the files it ships to npm. They are unminified, CJS/ESM, sourcemapped, and code splitting-friendly. They also are split in the manner that makes sense in the context of how this package is meant to be consumed.
