### ISSUE TITLE
RemoteHttpResolver example in README is missing the ".apply()" call

### ISSUE THREAD

**Issue by DenyVeyten** [mswjs/interceptors#582]
Example in README:
https://github.com/mswjs/interceptors/blob/e822e14bc669a7e5cefa9b9b0f627ea37c76ba99/README.md?plain=1#L524-L539

Missing line:
https://github.com/mswjs/interceptors/blob/e822e14bc669a7e5cefa9b9b0f627ea37c76ba99/test/features/remote/remote.test.ts#L33

Took me plenty of time to find out that `RemoteHttpResolver` starts working only after `resolver.apply()` has been called.

**Comment by kettanaito** [comment]
Hi, @DenyVeyten. Thanks for reporting this!

Yes, you have to call `.apply()` to enable any interceptor. `RemoteHttpResolver` extends that model. Looks like a documentation issue to me. 

Would you like to open a pull request to README to fix this?

**Comment by kettanaito** [comment]
## Released: v0.30.1 🎉

This has been released in v0.30.1!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.30.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.30.1)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
