### ISSUE TITLE
Cannot find module '@mswjs/interceptors/presets/browser' or its corresponding type declarations.

### ISSUE THREAD

**Issue by murnifine** [mswjs/interceptors#600]
🔴 ERROR  | Build failed. To debug, run plasmo dev --verbose.
🔴 ERROR  | Failed to resolve '@mswjs/interceptors/presets/browser' from './contents/intercept.ts'
🔴 ERROR  | Cannot load file './presets/browser' from module '@mswjs/interceptors'

**Comment by kettanaito** [comment]
Hi, @murnifine. Thanks for reporting this. Please provide a minimal reproduction for this issue. I'd be happy to look into it once you do. Thanks.
