### ISSUE TITLE
Can't resolve `_http_common` when using `msw@2.4.4`

### ISSUE THREAD

**Issue by kevva** [mswjs/interceptors#629]
When using `msw@2.4.4`, I get the following error when trying to build a TS package that depends on it:

```
Module not found: Can't resolve '_http_common'
```

The paths mapping obviously doesn't exist when published so it needs to be resolved correctly when building this module before publishing, not sure why `tsup` doesn't fix that.

**Comment by kevva** [comment]
It also doesn't make sense to me why you are importing and using interfaces/types from a `.d.ts` file. It's for the consumers of packages, not to be consumed by the package itself. Why  don't you just move the [`_http_common.d.ts`](https://github.com/mswjs/interceptors/pull/515/files#diff-f6f25e26d8056c21c061a8a1a21ded66de36d3e8c3baaac601accecf07641cbf) file to `src/interceptors/ClientRequest` somewhere (since it's only used there) and rename it to a `.ts` file? That would fix this issue.

**Comment by kevva** [comment]
[Here](https://codesandbox.io/p/devbox/nfx25q) is a replication case using a Next.js app without any config.

**Comment by kettanaito** [comment]
This has been fixed by #633. Please upgrade and verify.
