### ISSUE TITLE
XHR is broken in 0.34.3

### ISSUE THREAD

**Issue by robbtraister** [mswjs/interceptors#630]
It seems that a regression was introduced into the XMLHttpRequestController in the 0.34.3 release.

I have not yet been able to identify the root cause, but here is a [codesandbox](https://codesandbox.io/p/devbox/5xl3y2?file=/src/index.spec.ts:48,1-56,1) showing a test passing with `window.fetch()` and failing with `axios.put()`. The XHR request simply never returns and results in a timeout.

**Comment by robbtraister** [comment]
It looks like the request body has already been read/locked before we attempt to clone it (in order to determine `content-length`), where it is no longer cloneable.

**Comment by ddolcimascolo** [comment]
Hi all, posting here from https://github.com/mswjs/msw/issues/2273.

Anything I can do to help?

Thx,
David

**Comment by kettanaito** [comment]
## Released: v0.35.3 🎉

This has been released in v0.35.3!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.35.3)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.35.3)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
