### ISSUE TITLE
Incorrect absolute path for _http_common

### ISSUE THREAD

**Issue by sjoleee** [mswjs/interceptors#633]
![image](https://github.com/user-attachments/assets/ff292bbc-653d-46c5-945a-d7a45a4b50f9)

I found an error occurring when using MSW starting from version 2.4.4  
The cause seems to be an incorrect absolute path in mswjs/interceptor 0.35.0

```
//tsconfig.json

...
    "paths": {
      "_http_commons": ["./_http.common.d.ts"]
      // In the usage(MockHttpSocket.ts), _http_common is being used instead of _http_commons.
      // We do not have _http.common.d.ts, but instead have _http_common.d.ts.
    }
...
```

**Comment by kettanaito** [comment]
## Released: v0.35.2 🎉

This has been released in v0.35.2!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.35.2)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.35.2)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
