### ISSUE TITLE
Bug - Unhandled Requests with Custom Agent have wrong `this` context bound

### ISSUE THREAD

**Issue by tebriel** [mswjs/interceptors#635]
Thanks for reading my bug report, I'm new to this library and this was a tough one to track down based on the test failures I was seeing in my app.

## Description

When an intercepted request is not handled (`interceptor.on('request'...`) and the request uses a custom HTTP Agent, the custom agent's `createConnection` method is bound to the `MockHttpAgent`'s `this` context instead of the custom agent's `this` context, so methods/local variables are unavailable causing an exception.

## Steps to Reproduce

1. Create a Custom Agent
2. Implement `createConnection` and have it reference something else within itself (in my example, `this._noop()`.
3. Do *not* register a handler for the interceptor.
4. Code causes exception

### Repro Links

- Reproduction repo: https://github.com/tebriel/interceptors-bind
- [CustomAgent](https://github.com/tebriel/interceptors-bind/blob/main/src/agents.js)

## Location of Bug

[MockAgent](https://github.com/mswjs/interceptors/blob/0fff663c548da73caa2481b1d97da193d6df299d/src/interceptors/ClientRequest/agents.ts#L42-L44)

Specifically, it binds the `this` context of the `MockAgent` instead of the `this` of the `customAgent`.

## Additional question

Only the `createConnection` are bound from the custom agent, should the other methods from the custom agent be used?

**Comment by kettanaito** [comment]
## Released: v0.35.4 🎉

This has been released in v0.35.4!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.35.4)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.35.4)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
