### ISSUE TITLE
Headers instance is turned into an array

### ISSUE THREAD

**Issue by hugomrdias** [mswjs/interceptors#642]
Something is turning `Headers { 'content-type': 'application/json' }` into `[ [ 'content-type', 'application/json' ] ]` in node.

To be more specific 

```js
  const request = new Request(resource, {
    headers: new Headers(headers),
  })

  await fetch(resource)
  // request.headers is now an array
```

**Comment by kettanaito** [comment]
Hi, @hugomrdias. Can you provide a reproduction repo please? 

If `request.headers` is not an instance of `Headers`, there's a chance your environment is broken. If Interceptors is the one breaking it, I'd be happy to look into the repro and fix the issue. 

We've got a [sufficient test suite](https://github.com/mswjs/interceptors/blob/2a06bce76dddaeeeb38fc37f2d3e78fbe458ce23/src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts) to claim that we don't modify `request.headers` to be a different type out of the blue.

**Comment by hugomrdias** [comment]
starts with msw 2.4.4 and interceptors 0.35

**Comment by hugomrdias** [comment]
these fail if i update msw
https://github.com/hugomrdias/iso-repo/blob/main/packages/iso-web/test/request.test.js#L298-L332

**Comment by hugomrdias** [comment]
1. pnpm test:node inside iso-web package ( https://github.com/hugomrdias/iso-repo/blob/main/.github/CONTRIBUTING.md )
2. Just fails when getting a header with request.headers.get() which fails cause it's an array
3. Yeah 

Already tried to strip any trace of MSW and it works as expected also the same tests in a real browser works as expected. There's no weird envs here just straight node and reals browsers.

Pinned MSW to 2.4.3 and it's working now but 2.4.4 fails as I said previously.

As a side note the MSW folder inside iso-web may be interesting to you it's a wrapper to MSW to make the setup API the same for browser and node.
