### ISSUE TITLE
Intercepting POST-requests handled by ky http client throws an TypeError "this._options.headers.get is not a function"

### ISSUE THREAD

**Issue by inxmail-de-cln** [mswjs/interceptors#651]
When setting up intercepting POST-requests with MSW which are being handled by ky ( https://github.com/sindresorhus/ky  )  I ran into an TypeError "this._options.headers.get is not a function" being raised in this line: https://github.com/sindresorhus/ky/blob/3ba40cc6333cf1847c02c51744e22ab7c04407f5/source/core/Ky.ts#L181

Since this behaviour occurs in MSW versions later than 2.4.3  I guess the issue is being right filed here.

**Comment by paoloricciuti** [comment]
Just had the same problem with sveltekit...the problem is likely because this line

https://github.com/mswjs/interceptors/blob/2067cb0f57821a97f2cfb7aa9cdc2fd1900ed8ed/src/interceptors/ClientRequest/utils/recordRawHeaders.ts#L297

it's falling back to an empty array which is not an instance of `headers` so it doesn't have the `get` method on it.

**Comment by paoloricciuti** [comment]
Small update...it was actually not that PR but probably the one before that introduced the bug

https://github.com/mswjs/interceptors/pull/640/files

**Comment by kettanaito** [comment]
## Released: v0.36.5 🎉

This has been released in v0.36.5!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.36.5)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.36.5)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by inxmail-de-cln** [comment]
Thank you very much! This will help us a lot!
