### ISSUE TITLE
v0.36.6 TransformStream error

### ISSUE THREAD

**Issue by Nabrok** [mswjs/interceptors#663]
When this library updated to v0.36.6 my tests under vitest started giving this error:

```
ReferenceError: TransformStream is not defined
 ❯ ../node_modules/@mswjs/interceptors/src/interceptors/fetch/utils/brotli-decompress.ts:3:8
 ❯ ../test/server-mock.ts:1:1
      1| import { setupServer } from "msw/node";
       | ^
      2| import { handlers } from "~/mocks/handlers";
      3| 
```

Works fine with v0.36.5.

**Comment by z1ga** [comment]
I'm having the same issue with version `0.36.6`. Tested in an Expo app (expo version `51.0.28`) following [mswjs official react-native docs](https://mswjs.io/docs/integrations/react-native). I can confirm that downgrading to `0.36.5` fixes the issue.

**Comment by kettanaito** [comment]
Hi. Thanks for reporting this! Please, what is the version of Node.js you're using `node -v`? Note that Interceptors requires Node.js v18 or higher, which should ship the `TransformStream` class.

**Comment by Nabrok** [comment]
I'm using node v20.18.0.

**Comment by kettanaito** [comment]
If you are using jsdom, use [`jest-fixed-jsdom`](https://github.com/mswjs/jest-fixed-jsdom) as your environment. Also, if you can, migrate to HappyDOM or to in-browser testing with Vitest Browser mode or Playwright component tests.

**Comment by Nabrok** [comment]
I don't see how to use jest-fixed-jsdom with vitest, and happy-dom gives the same problem.

**Comment by kettanaito** [comment]
@Nabrok, we are running the entire test suite against Vitest and sometimes HappyDOM. Try looking around, maybe something is interfering. If you find nothing, raise an issue with HappyDOM.

**Comment by Nabrok** [comment]
I had `pool` set to `vmThreads` in the test config, and that was causing happy-dom not to see `TextEncoder`.

I removed that option and happy-dom seems happy.

My tests are now passing with v0.36.10.
