### ISSUE TITLE
MSW with supertest get request is trying to listen as socket request.

### ISSUE THREAD

**Issue by Ajitprai** [mswjs/interceptors#687]
supertest .get request with .send({}) was causing the msw to think its a socket request as I think we can only send data in get request if its a socket request.

And we dont have any handler for socket request only https.

**Comment by kettanaito** [comment]
Hi, @Ajitprai. Do you have a reproduction repo for this, please? I must admit, I don't understand what you mean by a "socket request". Any request in Node.js will tap into `net.Socket`, so I presume you mean something else. 

Please share a repo and then we can discuss the problem.
