### ISSUE TITLE
Its broken

### ISSUE THREAD

**Issue by radiantone** [mswjs/interceptors#689]
This doesn't work. Doesn't resolve.

import { RequestInterceptors } from 'node-request-interceptor'
import { interceptXMLHttpRequest } from 'node-request-interceptor/interceptors/XMLHttpRequest'

**Comment by radiantone** [comment]
![interceptor](https://github.com/user-attachments/assets/dd118d54-d99f-4584-a571-a78cab5c0be7)

**Comment by radiantone** [comment]
In addition to the above not working because the author cannot spell their own packages/classes/directories, but when I fixed that, the behavior explained does not even work. it does not intercept ANY outgoing calls. Complete fail.

**Comment by kettanaito** [comment]
You are using a library that's years old and is discontinued. 

```
npm i @mswjs/interceptors
```
