### ISSUE TITLE
React native - Can't find variable: Buffer

### ISSUE THREAD

**Issue by Federkun** [mswjs/interceptors#80]
Hi all! I just have enough time to log the issue: this is something introduced by https://github.com/mswjs/node-request-interceptor/pull/75 ; `Buffer` is one of those global vars that don't exists in RN. This is not a critical issue, as even on the user's side a simple `global.Buffer = bufferPolyfill` will do to fix the issue. Another alternative is to relay on https://www.npmjs.com/package/buffer directly from this package

**Comment by kettanaito** [comment]
Hey, @Federkun. Nice to hear again from you!

I wonder if there's an alternative approach to create a buffer from the response body, apart from using `Buffer.from`.

**Comment by kettanaito** [comment]
There's been a chunk of improvements implemented by @wwdrew that concern React Native operability:

- https://github.com/mswjs/msw/pull/808
- https://github.com/mswjs/msw/pull/809

I believe that the React Native usage is functional now. 

There's an effort to add the React Native example in https://github.com/mswjs/examples/pull/60.
